FROM node:20-alpine

WORKDIR /app

# 1. Dependencies
COPY package*.json ./
RUN npm install

# 2. App source
COPY . .

# 3. Runtime port (Vite default)
EXPOSE 5173

# 4. Start using dev script from package.json
CMD ["npm", "run", "dev"]